#!/usr/bin/python2
from sys import argv
import qubesmanager.advanced

if len(argv) > 1:
	qubesmanager.advanced.main(argv[1])
else:
	print "Specify name of the qube you would like to edit\n"
	print "	qubes-manager-advanced <qube-name>\n"
