# Test Data

def values():
	vms = [{
		"type": "app",
		"icon": "anonymous-32",
		"name": "web-anon",
		"desc": "Web Anonymous",
		"netvm": "sys-whonix",
		"disk_utilization": 2853,
		"private_img_sz": 4096,
		"include_in_backups": True,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": False,
		"get_power_state": "Running",
		"is_fully_usable": True,
		"is_guid_running": True,
		"is_networked": True,
		"is_outdated": True,
		"updateable": False
	},{
		"type": "app",
		"icon": "bitcoin-32",
		"name": "bitcoin",
		"desc": "Bitcoin",
		"netvm": "sys-whonix",
		"disk_utilization": 327,
		"private_img_sz": 2048,
		"include_in_backups": True,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": False,
		"get_power_state": "Halted",
		"is_fully_usable": False,
		"is_guid_running": False,
		"is_networked": True,
		"is_outdated": False,
		"updateable": False
	},{
		"type": "app",
		"icon": "vault-32",
		"name": "vault",
		"desc": "Vault",
		"netvm": None,
		"disk_utilization": 272,
		"private_img_sz": 2048,
		"include_in_backups": True,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": True,
		"get_power_state": "Running",
		"is_fully_usable": True,
		"is_guid_running": True,
		"is_networked": False,
		"is_outdated": True,
		"updateable": False
	},{
		"type": "app",
		"icon": "mailpile-32",
		"name": "mailpile",
		"desc": "Mailpile",
		"netvm": "sys-whonix",
		"disk_utilization": 5278,
		"private_img_sz": 10485,
		"include_in_backups": True,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": True,
		"get_power_state": "Running",
		"is_fully_usable": True,
		"is_guid_running": True,
		"is_networked": True,
		"is_outdated": True,
		"updateable": False
	},{
		"type": "app",
		"icon": "default",
		"name": "email-work",
		"desc": "Email Work",
		"netvm": "sys-bitmask",
		"disk_utilization": 7421,
		"private_img_sz": 14248,
		"include_in_backups": True,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": False,
		"get_power_state": "Halted",
		"is_fully_usable": False,
		"is_guid_running": False,
		"is_networked": True,
		"is_outdated": False,
		"updateable": False
	},{
		"type": "app",
		"icon": "default",
		"name": "personal",
		"desc": "Personal",
		"netvm": None,
		"disk_utilization": 11045,
		"private_img_sz": 18960,
		"include_in_backups": True,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": False,
		"get_power_state": "Halted",
		"is_fully_usable": False,
		"is_guid_running": False,
		"is_networked": False,
		"is_outdated": False,
		"updateable": False
	},{
		"type": "app",
		"icon": "qube-color-32",
		"name": "dev",
		"desc": "Development",
		"netvm": "sys-whonix",
		"disk_utilization": 40835,
		"private_img_sz": 45960,
		"include_in_backups": True,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": False,
		"get_power_state": "Running",
		"is_fully_usable": True,
		"is_guid_running": True,
		"is_networked": True,
		"is_outdated": False,
		"updateable": False
	},{
		"type": "net",
		"icon": "default",
		"name": "sys-net",
		"desc": "Wifi & Ethernet",
		"netvm": None,
		"disk_utilization": 294,
		"private_img_sz": 2048,
		"include_in_backups": False,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": True,
		"get_power_state": "Running",
		"is_fully_usable": True,
		"is_guid_running": True,
		"is_networked": True,
		"is_outdated": True,
		"updateable": False
	},{
		"type": "net",
		"icon": "default",
		"name": "sys-firewall",
		"desc": "Firewall",
		"netvm": "sys-net",
		"disk_utilization": 165,
		"private_img_sz": 2048,
		"include_in_backups": False,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": True,
		"get_power_state": "Running",
		"is_fully_usable": True,
		"is_guid_running": True,
		"is_networked": True,
		"is_outdated": True,
		"updateable": False
	},{
		"type": "net",
		"icon": "default",
		"name": "sys-bitmask",
		"desc": "Bitmask (VPN)",
		"netvm": "sys-firewall",
		"disk_utilization": 385,
		"private_img_sz": 2048,
		"include_in_backups": False,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": False,
		"get_power_state": "Running",
		"is_fully_usable": True,
		"is_guid_running": True,
		"is_networked": True,
		"is_outdated": False,
		"updateable": False
	},{
		"type": "net",
		"icon": "default",
		"name": "sys-whonix",
		"desc": "Tor",
		"netvm": "sys-firewall",
		"disk_utilization": 512,
		"private_img_sz": 2048,
		"include_in_backups": False,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": True,
		"get_power_state": "Running",
		"is_fully_usable": True,
		"is_guid_running": True,
		"is_networked": True,
		"is_outdated": False,
		"updateable": False
	},{
		"type": "sys",
		"icon": "usb-32",
		"name": "usbdata",
		"desc": "USB",
		"netvm": None,
		"disk_utilization": 365,
		"private_img_sz": 2048,
		"include_in_backups": False,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": True,
		"get_power_state": "Running",
		"is_fully_usable": True,
		"is_guid_running": True,
		"is_networked": False,
		"is_outdated": True,
		"updateable": False
	},{
		"type": "sys",
		"icon": "sd-card-32",
		"name": "sddata",
		"desc": "SD Card",
		"netvm": None,
		"disk_utilization": 275,
		"private_img_sz": 2048,
		"include_in_backups": False,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": True,
		"get_power_state": "Halted",
		"is_fully_usable": True,
		"is_guid_running": False,
		"is_networked": False,
		"is_outdated": False,
		"updateable": False
	},{
		"type": "dev",
		"icon": "harddrive-32",
		"name": "usbdata",
		"desc": "Main Backup",
		"netvm": None,
		"disk_utilization": 150000,
		"private_img_sz": 221500,
		"include_in_backups": False,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": False,
		"get_power_state": "Mounted",
		"is_fully_usable": True,
		"is_guid_running": True,
		"is_networked": False,
		"is_outdated": False,
		"updateable": False
	},{
		"type": "template",
		"icon": "fedora-32",
		"name": "fedora-23",
		"desc": "Fedora",
		"netvm": "sys-whonix",
		"disk_utilization": 6600,
		"private_img_sz": 10642,
		"include_in_backups": False,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 0,
		"autostart": False,
		"get_power_state": "Halted",
		"is_fully_usable": False,
		"is_guid_running": False,
		"is_networked": True,
		"is_outdated": False,
		"updateable": False
	},{
		"type": "template",
		"icon": "debian-32",
		"name": "debian-8",
		"desc": "Debian",
		"netvm": "sys-whonix",
		"disk_utilization": 8450,
		"private_img_sz": 12225,
		"include_in_backups": True,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 1455479829,
		"autostart": False,
		"get_power_state": "Halted",
		"is_fully_usable": False,
		"is_guid_running": False,
		"is_networked": True,
		"is_outdated": False,
		"updateable": True
	},{
		"type": "template",
		"icon": "template-32",
		"name": "whonix-gw",
		"desc": "Whonix Gateway",
		"netvm": "sys-whonix",
		"disk_utilization": 4450,
		"private_img_sz": 6225,
		"include_in_backups": False,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 0,
		"autostart": False,
		"get_power_state": "Halted",
		"is_fully_usable": True,
		"is_guid_running": False,
		"is_networked": True,
		"is_outdated": True,
		"updateable": False
	},{
		"type": "template",
		"icon": "template-32",
		"name": "whonix-ws",
		"desc": "Whonix Workstation",
		"netvm": "sys-whonix",
		"disk_utilization": 6225,
		"private_img_sz": 8192,
		"include_in_backups": False,
		"last_run_timestamp": 1455654332,
		"backup_timestamp": 0,
		"autostart": False,
		"get_power_state": "Halted",
		"is_fully_usable": True,
		"is_guid_running": False,
		"is_networked": True,
		"is_outdated": True,
		"updateable": False
	}]
	return vms

def get_qube_by_name(name):
	qubes = values()
	for qube in qubes:
		if qube["name"] == name:
			return qube

def get_disk_utilization(qube):
	return qube["disk_utilization"]

def get_private_img_sz(qube):
	return qube["private_img_sz"]
